# set XDG Base Directories

if [[ -z "$XDG_CONFIG_HOME" ]]
then
    export XDG_CONFIG_HOME="$HOME/.config"
fi
if [[ -z "$XDG_DATA_HOME" ]]
then
    export XDG_DATA_HOME="$HOME/.local/share"
fi
if [[ -z "$XDG_STATE_HOME" ]]
then
    export XDG_STATE_HOME="$HOME/.local/state"
fi
if [[ -z "$XDG_CASHE_HOME" ]]
then
    export XDG_CACHE_HOME="$HOME/.cache"
fi


# set bash Options
[[ -f $BDOTDIR/options ]] && . $BDOTDIR/options

# set CLI tools
[[ -f $BDOTDIR/cmdtools ]] && . $BDOTDIR/cmdtools

# set alias definitions
[[ -f $BDOTDIR/aliases ]] && . $BDOTDIR/aliases
