# XDG Base Directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# bash user configuration directory
export BASH_DOTDIR="$XDG_CONFIG_HOME/bash"

# either set bat as man pager
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"
# or define man wrapping function using bat piping
# man() {
#   command man "$@" | bat -l man -p
# }

# set function to highlight --help messages
# how to use: help <command> like 'help col'
help() {
    "$@" --help 2>&1 | bat -l help -p 
}

# source configuration files by categories
[ -f $BASH_DOTDIR/options ] && . $BASH_DOTDIR/options
[ -f $BASH_DOTDIR/aliases ] && . $BASH_DOTDIR/aliases
[ -f $BASH_DOTDIR/commands ] && . $BASH_DOTDIR/commands
